apply plugin: "java-library"
apply plugin: "maven-publish"

ext.pluginNameUpper = "DeathChest"
ext.pluginNameLower = ext.pluginNameUpper.toLowerCase()
ext.majorVersion = 5
ext.minorVersion = 1
ext.minecraftVersion = "1.21.11"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

// Supplied by Jenkins
ext.buildNumber = System.env.BUILD_NUMBER == null ? "x"                : "$System.env.BUILD_NUMBER"
ext.mavenDirectory = System.env.MAVEN_DIR == null ? "$projectDir/repo" : "$System.env.MAVEN_DIR"
ext.jdDirectory = System.env.JAVADOCS_DIR == null ? null               : "$System.env.JAVADOCS_DIR"

group = "cat.nyaa"
version = "$majorVersion.$minorVersion.$buildNumber".toString()

base {
    archivesName = 'DeathChest'
}

repositories {
    mavenCentral()
    maven {
        name 'papermc'
        url 'https://repo.papermc.io/repository/maven-public/'
    }
    maven {
        name 'NyaaCat'
        url 'https://ci.nyaacat.com/maven/'
    }
}
dependencies {
    compileOnly "io.papermc.paper:paper-api:$minecraftVersion-R0.1-SNAPSHOT"

    // other nyaa plugins
    compileOnly('cat.nyaa:nyaacore:9.10') { transitive = false }

    //test
    testImplementation(platform('org.junit:junit-bom:5.10.3'))
    testImplementation('org.junit.jupiter:junit-jupiter:5.10.3')

}

processResources {
    filesMatching("**/plugin.yml") {
        expand 'version': project.version
    }
}

task sourcesJar(type: Jar) {
    archiveClassifier.set('sources')
    from sourceSets.main.java.srcDirs
}

// extra compile warnings
compileJava {
    options.compilerArgs += ["-Xlint:deprecation"]
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
