language: zh-CN
enabled: true
dropAmount: 0-16
removeTime: 600
openSelfChestOnly: true
enabledWorld:
  - world
  - world_nether
  - world_the_end
keepArmors: false
keepBelt: false
keepOffhand: false
respawnBuff: true
respawn_effect:
  - speed:2:1200 # 1200 tick 速度 3
  - resistance:1:1200
  - weakness:1:1200