name: DeathChest
main: cat.nyaa.deathchest.DeathChestPlugin
version: 1.0
depend: [NyaaCore]
api-version: 1.15
commands:
  deathchest:
    description: Create a chest and take some of the items from a player when they die.
    aliases: dc
    usage: /<command>
    permission: dc
    permission-message: You don't have <permission>

permissions:
  dc.command:
    description: Base permission node for commands
    default: true
  dc.unlock:
    description: Permission node for unlocking deathchests
    default: true
