name: DeathChest
main: cat.nyaa.deathchest.DeathChestPlugin
version: 1.0
depend: [NyaaCore]
api-version: 1.13
commands:
  deathchest:
    description: Create a chest and take some of the items from a player when they die.
    usage: /<command>
    permission: deathchest.commands
    permission-message: You don't have <permission>
